### PR TITLE
Add warnOnFailure option to checkSorted

### PR DESCRIPTION
**Pull request by liu15**
This update was part of Al's faces update.

### CODE REVIEW

**Review by dtaller — APPROVED** [review]

**Comment by adayton1** [comment]
Did you mean to change BLT? I just updated it to the latest version, so I'm worried you might have accidentally reverted that.

**Review by adayton1 — CHANGES_REQUESTED** [review]
Did you mean to change BLT? I just updated it to the latest version, so I'm worried you might have accidentally reverted that.

**Comment by liu15** [comment]
> Did you mean to change BLT? I just updated it to the latest version, so I'm worried you might have accidentally reverted that.

Definitely did not.  I'll fix it.

**Review by adayton1 — APPROVED** [review]
LGTM

**Pull request merged**
