### PR TITLE
Enable tests in CI

### PR DESCRIPTION
**Pull request by adrienbernede**
Test were turned OFF in CI !

### CODE REVIEW

**Comment by adrienbernede** [comment]
@adayton1 Could you please have a look at the build failure ?
https://lc.llnl.gov/gitlab/care/CARE/-/jobs/2241570
https://lc.llnl.gov/gitlab/care/CARE/-/jobs/2241506

**Comment by adayton1** [comment]
> @adayton1 Could you please have a look at the test build failure ? https://lc.llnl.gov/gitlab/care/CARE/-/jobs/2241570 https://lc.llnl.gov/gitlab/care/CARE/-/jobs/2241506

I will take a look.

**Comment by adayton1** [comment]
> > @adayton1 Could you please have a look at the test build failure ? https://lc.llnl.gov/gitlab/care/CARE/-/jobs/2241570 https://lc.llnl.gov/gitlab/care/CARE/-/jobs/2241506
> 
> I will take a look.

Does this fix the issue? https://github.com/LLNL/CARE/pull/304/files

**Comment by adayton1** [comment]
Some of the failures occur because CARE now requires c++17, but I haven't updated that in the CI or added checks in the build system for it yet.

**Comment by adrienbernede** [comment]
@adayton1,
I added what seemed necessary at the Spack level, which should reflect in the CMakeCache file.
However, I did not add the CMake checks (yet).
Still, it looks like there are new compilers errors to deal with.

**Pull request closed without merging**
