### PR TITLE
Pinned memory space for scan loops

### PR DESCRIPTION
**Pull request by mrowan137**
This PR provides the option to select SCAN loop memory space (`chai::PINNED` or `chai::GPU`).

### CODE REVIEW

**Review by adayton1 — APPROVED** [review]
LGTM

**Review by liu15 — APPROVED** [review]
Looks good!

**Review by robinson96 — APPROVED** [review]
LGTM

**Comment by adayton1** [comment]
I don't think the CI will run from a fork, so I created a branch in CARE and a new pull request so that the CI will run (RAJA follows this model).

**Pull request merged**
