### PR TITLE
Update to BLT v0.4.0

### PR DESCRIPTION
**Pull request by adayton1**

### CODE REVIEW

**Review by dtaller — APPROVED** [review]
Looks good to me. I assume you are updating this for HIP related fixes?

**Comment by dtaller** [comment]
Actually it  looks like tests failed, I should have looked more closely . I'll look at this again when that is sorted out.

**Comment by adayton1** [comment]
The tests actually failed due to the default environment on GitHub servers being updated (looks like a newer cmake caused the problem). Ben just put up a pull request to fix that, so we should be good to go.

**Comment by adayton1** [comment]
Yeah, BLT v0.4.0 has better support for HIP.

**Comment by dtaller** [comment]
> Yeah, BLT v0.4.0 has better support for HIP.

Yes, previously we made incremental hip related changes to blt and built care with blt develop. If this fixed version has all the HIP fixes we need, it will make development easier. Thanks!

**Review by liu15 — APPROVED** [review]

**Pull request merged**
