### PR TITLE
[woptim] Update radiuss-shared-ci to new release (with radiuss-spack-configs)

### PR DESCRIPTION
**Pull request by adrienbernede**
This PR updates the GitLab Shared CI to the latest release (v2023.09.0).

This release removes any relationship to Spack in the Shared CI.
In particular, the RADIUSS Shared jobs moved to RADIUSS Spack Configs.

### CODE REVIEW

**Comment by adrienbernede** [comment]
@adayton1 I have good faith into seeing the test passing once the CI is triggered.

**Comment by adrienbernede** [comment]
And now we will have to wait until the end of corona and tioga maintenance.

**Review by adayton1 — APPROVED** [review]
LGTM

**Review by robinson96 — APPROVED** [review]
LGTM

**Review by liu15 — APPROVED** [review]

**Comment by adayton1** [comment]
@adrienbernede, is this good to go ahead and merge?

**Comment by adrienbernede** [comment]
Yes

**Comment by adayton1** [comment]
Thanks, @adrienbernede !

**Pull request merged**
