### PR TITLE
Use perfect forwarding for lambdas

### PR DESCRIPTION
**Pull request by adayton1**
Avoid unnecessary copies of temporary lambdas passed to RAJA.
Also remove unnecessary macros.

### CODE REVIEW

**Comment by dtaller** [comment]
Looks good to me! Thanks for the update

**Review by dtaller — APPROVED** [review]

**Comment by dtaller** [comment]
When you push this update into client codes let me know if / how much improvement you see from the perfect forwarding, curious to see.

**Review by robinson96 — APPROVED** [review]
LGTM. Have we measured a performance improvement?

**Review by agcapps — APPROVED** [review]
Thanks, Alan.

**Review by liu15 — APPROVED** [review]

**Comment by adayton1** [comment]
There seems to be a slight (1.01x) improvement in some application testing. I don't have benchmarks for it in CARE at the moment, though.

**Pull request merged**
