### PR TITLE
Update toolchains on tioga, lassen, ruby and poodle

### PR DESCRIPTION
**Pull request by adrienbernede**
- [x] Remove Intel 19
- [x] Update to Intel 2023
- [x] ~~Update corona to ROCm 6.0.2~~ -> same error as with tioga, need ROCm 6.1.x , reverted to ROCm 5.7.1
- [x] Update tioga to ROCm 6.1.2
- [x] Remove CUDA 10 job (blueos system default is now 11.2.0)

### CODE REVIEW

**Review by adayton1 — APPROVED** [review]
LGTM

**Review by liu15 — APPROVED** [review]

**Comment by adrienbernede** [comment]
@adayton1 This is ready.

**Review by adayton1 — APPROVED** [review]
LGTM

**Comment by adayton1** [comment]
> @adayton1 This is ready.

Thanks, @adrienbernede !

**Pull request merged**
